python3 ../supervised_t5.py \
    --model_name_or_path t5-small \
    --tokenizer_name_or_path t5-small \
    --max_input_length 128 \
    --max_target_length 128 \
    --task_type T2A \
    --absa_tuple ACOP \
    --annotations_text_type gas_extraction_style \
    --text_column text \
    --annotations_column annotations \
    --annotations_raw_format acpo \
    --annotation_flag \
    --dataset_name Rest16 \
    --dataset_path  \
    --train_size 0.8 \
    --val_size 0.1 \
    --test_size 0.1 \
    --lang en \
    --verbose \
    parser.set_defaults(verbose=True \
    --verbose_every 1 \
    --exp_name  \
    --random_state 42 \
    --n_epochs 10 \
    --batch_size 16 \
    --lr 0.001 \
    --save_every 10 \
    --save_model_path  \
    --train_flag \
    --save_eval_results \
    --eval_res_file_path  \
    --lower_flag \
